development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") %>
  channel_prefix: Jaipur_production
  ssl_params:
    verify_mode: OpenSSL::SSL::VERIFY_PEER

    # verify_mode: OpenSSL::SSL::VERIFY_NONE
    # ca_file: <%= ENV.fetch("REDIS_CA_FILE_PATH", nil) %>
